# Generated by Django 5.0.6 on 2024-12-06 08:55

import datetime
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=40)),
                ('place', models.CharField(max_length=100)),
                ('bank_account_number', models.CharField(max_length=26)),
                ('is_alive', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('birth_date', models.DateField(default=datetime.date(2000, 3, 24))),
                ('phone_num', models.IntegerField(default=123456789)),
                ('place_of_residence', models.CharField(default='Brak Danych', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('household_type', models.CharField(choices=[('single', 'Jednoosobowe'), ('multiple', 'Wieloosobowe')], max_length=20)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.beneficiary')),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.benefit')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('applications', models.ManyToManyField(related_name='application_lists', to='frontend.application')),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.benefit')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalBeneficiary',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=40)),
                ('place', models.CharField(max_length=100)),
                ('bank_account_number', models.CharField(max_length=26)),
                ('is_alive', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('birth_date', models.DateField(default=datetime.date(2000, 3, 24))),
                ('phone_num', models.IntegerField(default=123456789)),
                ('place_of_residence', models.CharField(default='Brak Danych', max_length=150)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical beneficiary',
                'verbose_name_plural': 'historical beneficiarys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.beneficiary')),
                ('payment_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.paymentlist')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentListBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.beneficiary')),
                ('payment_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.paymentlist')),
            ],
            options={
                'unique_together': {('payment_list', 'beneficiary')},
            },
        ),
        migrations.AddField(
            model_name='paymentlist',
            name='Beneficiaries',
            field=models.ManyToManyField(related_name='payments', through='frontend.PaymentListBeneficiary', to='frontend.beneficiary'),
        ),
    ]
