# Generated by Django 5.0.6 on 2024-06-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='is_alive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='payment_year',
            field=models.IntegerField(default=2022),
        ),
    ]
