# Generated by Django 5.0.6 on 2024-06-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_beneficiary_is_alive_alter_beneficiary_payment_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
