# Generated by Django 5.0.6 on 2024-07-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_beneficiary_phone_num_beneficiary_place_of_residence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='phone_num',
            field=models.IntegerField(default=0, max_length=9),
        ),
        migrations.AlterField(
            model_name='historicalbeneficiary',
            name='phone_num',
            field=models.IntegerField(default=0, max_length=9),
        ),
    ]
