# Generated by Django 5.0.6 on 2024-07-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_alter_beneficiary_phone_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='phone_num',
            field=models.IntegerField(default=123456789),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='place_of_residence',
            field=models.CharField(default='Brak Danych', max_length=150),
        ),
        migrations.AlterField(
            model_name='historicalbeneficiary',
            name='phone_num',
            field=models.IntegerField(default=123456789),
        ),
        migrations.AlterField(
            model_name='historicalbeneficiary',
            name='place_of_residence',
            field=models.CharField(default='Brak Danych', max_length=150),
        ),
    ]
