# Generated by Django 5.0.6 on 2024-07-04 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_benefit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('household_type', models.CharField(choices=[('single', 'Jednoosobowe'), ('multiple', 'Wieloosobowe')], max_length=20)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.beneficiary')),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.benefit')),
            ],
        ),
    ]
