# Generated by Django 5.0.6 on 2024-07-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_application_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
